name: Python

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
    branches: [main]

jobs:
  build:
    name: Wasi Python
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: startsWith( github.ref, 'refs/tags/v')

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Base Image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: false
          load: true
          tags: wasi-build
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Python
        run: |
          pwd
          ls -la
          docker run --rm -v $(pwd):$(pwd) -w $(pwd) wasi-build:latest /bin/bash -c 'export PATH=$PATH:/root/.wasmtime/bin; ./run.sh'
          ls -la

      - name: Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./wasi-python3.*.wasm
